# Generated by Django 2.0.4 on 2018-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('answer', models.TextField()),
                ('source_hint', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
